#!/usr/bin/env python3
"""Regenerate the ground-truth probes of verify_image.py: probe.tif + probe.gpkg.

Why this script exists: the probes were first generated by hand with osgeo
inside a guest and copied out; the recipe lived only in that session. The band
checksum depends on the pixel values and the vector truth on the feature
coordinates, none of which were on disk, so a damaged probe could not be
rebuilt equivalently. This script is that recipe.

Run it in the guest or on any machine with osgeo (the GDAL Python bindings):
    python3 make_probe.py [output dir]      # default: the directory of this script (probe/)

Byte-for-byte reproduction is not guaranteed (GeoPackage carries timestamps
and other volatile metadata; the existing probe stores unit_id as MEDIUMINT
while a regenerated one may say INTEGER, which SQLite affinity treats alike).
Equivalence means TRUTH below, which is kept in sync with TIF_TRUTH/GPKG_TRUTH
in ../verify_image.py and with the truth table in README.md (see README.md
for the obligation). After writing, the files are read back and checked
against TRUTH; any mismatch exits non-zero.
"""
from __future__ import annotations

import pathlib
import struct
import sys

from osgeo import gdal, ogr, osr

# Recent osgeo warns unless the exception mode is chosen explicitly; and on error we
# want an exception, not a silent None
gdal.UseExceptions()
ogr.UseExceptions()
osr.UseExceptions()

# ── recipe parameters (changing any of them changes the truth: read README.md first) ──
EPSG = 32633                                          # UTM 33N; probe only, unrelated to task assets
SIZE = 64                                             # 64×64: small enough that upload and read-back take seconds
GT = (500000.0, 10.0, 0.0, 4649776.0, 0.0, -10.0)     # origin (500000, 4649776), 10 m pixels


def pixel(row: int, col: int) -> int:
    """Pixel value formula (uint16). checksum=48341 is fixed by it alone: GDAL's
    Checksum is a rotating modulus sum over the eleven primes {7, 11, ..., 43}
    (gdalchecksum.cpp), not a plain sum, so any change here changes the checksum."""
    return row + col


# probe_units: three 80×80 m squares (PolygonZ with z=0, same type as the existing probe),
# offset by 100 m along x, unit_id = 1..3
SQUARES = [(1, 500000.0), (2, 500100.0), (3, 500200.0)]   # (unit_id, x0)
SQUARE_Y0, SQUARE_EDGE = 4649000.0, 80.0

TRUTH = {   # for the self-check; same keys and values as the two TRUTH dicts in verify_image.py
    "tif": {"epsg": "32633", "size": "64x64", "origin_x": "500000", "checksum": 48341},
    "gpkg": {"layer": "probe_units", "features": 3, "epsg": "32633"},
}


def _srs() -> osr.SpatialReference:
    s = osr.SpatialReference()
    s.ImportFromEPSG(EPSG)
    return s


def make_tif(path: pathlib.Path) -> None:
    ds = gdal.GetDriverByName("GTiff").Create(str(path), SIZE, SIZE, 1, gdal.GDT_UInt16)
    ds.SetProjection(_srs().ExportToWkt())
    ds.SetGeoTransform(GT)
    buf = struct.pack(f"<{SIZE * SIZE}H",
                      *(pixel(r, c) for r in range(SIZE) for c in range(SIZE)))
    ds.GetRasterBand(1).WriteRaster(0, 0, SIZE, SIZE, buf, buf_type=gdal.GDT_UInt16)
    ds.FlushCache()
    ds = None


def make_gpkg(path: pathlib.Path) -> None:
    if path.exists():
        path.unlink()      # GPKG opens an existing file; without this the layer is added to the old one
    ds = ogr.GetDriverByName("GPKG").CreateDataSource(str(path))
    lyr = ds.CreateLayer("probe_units", _srs(), ogr.wkbPolygon25D)
    lyr.CreateField(ogr.FieldDefn("unit_id", ogr.OFTInteger))
    for unit_id, x0 in SQUARES:
        y0, e = SQUARE_Y0, SQUARE_EDGE
        wkt = (f"POLYGON Z (({x0} {y0} 0,{x0 + e} {y0} 0,{x0 + e} {y0 + e} 0,"
               f"{x0} {y0 + e} 0,{x0} {y0} 0))")
        f = ogr.Feature(lyr.GetLayerDefn())
        f.SetField("unit_id", unit_id)
        f.SetGeometry(ogr.CreateGeometryFromWkt(wkt))
        lyr.CreateFeature(f)
        f = None
    ds = None


def selfcheck(tif: pathlib.Path, gpkg: pathlib.Path) -> list[str]:
    """Read the freshly written probes back and compare them with TRUTH item by item;
    returns the mismatches (empty = pass). Reads the same way the calibration code
    in verify_image.py does inside the guest, so the same values are checked."""
    errs: list[str] = []

    ds = gdal.Open(str(tif))
    srs = osr.SpatialReference(wkt=ds.GetProjection())
    got_tif = {"epsg": srs.GetAuthorityCode(None),
               "size": f"{ds.RasterXSize}x{ds.RasterYSize}",
               "origin_x": f"{ds.GetGeoTransform()[0]:.0f}",
               "checksum": ds.GetRasterBand(1).Checksum()}
    ds = None
    for k, want in TRUTH["tif"].items():
        if got_tif[k] != want:
            errs.append(f"tif.{k}: got {got_tif[k]!r}, want {want!r}")

    ds = ogr.Open(str(gpkg))
    lyr = ds.GetLayer(0)
    got_gpkg = {"layer": lyr.GetName(),
                "features": lyr.GetFeatureCount(),
                "epsg": lyr.GetSpatialRef().GetAuthorityCode(None)}
    ds = None
    for k, want in TRUTH["gpkg"].items():
        if got_gpkg[k] != want:
            errs.append(f"gpkg.{k}: got {got_gpkg[k]!r}, want {want!r}")

    print(f"  tif : {got_tif}")
    print(f"  gpkg: {got_gpkg}")
    return errs


def main() -> int:
    out = (pathlib.Path(sys.argv[1]) if len(sys.argv) > 1
           else pathlib.Path(__file__).resolve().parent)
    out.mkdir(parents=True, exist_ok=True)
    tif, gpkg = out / "probe.tif", out / "probe.gpkg"

    make_tif(tif)
    make_gpkg(gpkg)
    errs = selfcheck(tif, gpkg)
    if errs:
        print("FAIL: the generated probes do not match TRUTH (recipe changed? osgeo behaviour drift?):")
        for e in errs:
            print(f"     {e}")
        return 1
    print(f"OK: probes written and self-checked: {tif} / {gpkg}")
    print("   If you replaced the probes in probe/: check TIF_TRUTH / GPKG_TRUTH in verify_image.py"
          " and the truth table in README.md, as README.md requires.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
